### ISSUE TITLE
Failed to activate the atom-css-comb package

### ISSUE THREAD

**Issue by mfucek1** [jchouse/csscomb-atom#32]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [atom-css-comb](https://github.com/jchouse/csscomb-atom) package 3.1.0

### Stack Trace

Failed to activate the atom-css-comb package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/composite-disposable.js:74:1)
    at CompositeDisposable.module.exports.CompositeDisposable.add (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/composite-disposable.js:43:1)
    at Package.module.exports.Package.activateKeymaps (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:374:1)
    at Package.module.exports.Package.activateResources (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:341:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:221:1
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:99:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:218:1
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:215:1)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.17.2/resources/app/src/package-manager.js:642:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/package-manager.js:623:1
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.17.2/resources/app/src/config.js:346:1)
    at PackageManager.module.exports.PackageManager.activatePackages (~/AppData/Local/atom/app-1.17.2/resources/app/src/package-manager.js:618:1)
    at PackageManager.module.exports.PackageManager.activate (~/AppData/Local/atom/app-1.17.2/resources/app/src/package-manager.js:600:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/atom-environment.js:832:1
```

### Commands

```
     -0:22.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-css-comb 3.1.0 
autoclose-html 0.23.0 
emmet 2.4.3 
file-icons 2.1.6 
fonts 2.1.0 
highlight-selected 0.13.1 
minimap 4.28.2 
minimap-highlight-selected 4.6.1 
pigments 0.39.1 
todo-show 1.11.0 
```

**Comment by jchouse** [comment]
I updated the package. Today I will test under Windows

**Comment by jchouse** [comment]
cannot reproduce

**Comment by EkaterinaNoAsanebou** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Mac OS X 10.13.5
**Thrown From**: [atom-css-comb](https://github.com/jchouse/csscomb-atom) package 3.3.1


### Stack Trace

Failed to activate the atom-css-comb package

```
At only one instance of babel-polyfill is allowed

Error: only one instance of babel-polyfill is allowed
    at /packages/atom-css-comb/node_modules/babel-polyfill/lib/index.js:10:9)
    at /packages/atom-css-comb/node_modules/babel-polyfill/lib/index.js:29:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-css-comb/node_modules/csscomb/lib/core.js:3:1)
    at /packages/atom-css-comb/node_modules/csscomb/lib/core.js:453:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-css-comb/node_modules/csscomb/lib/csscomb.js:5:12)
    at /packages/atom-css-comb/node_modules/csscomb/lib/csscomb.js:306:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-css-comb/lib/css-comb.js:3:41)
    at /packages/atom-css-comb/lib/css-comb.js:152:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:220:40)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:206:33)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:866:28)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:871:27)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.32.5 
atom-clock 0.1.16 
atom-css-comb 3.3.1 
autoclose-html 0.23.0 
autocomplete-paths 2.12.2 
busy-signal 1.4.3 
color-picker 2.3.0 
double-tag 1.5.0 
emmet 2.4.3 
git-plus 7.12.0 
git-plus-toolbar 1.0.1 
highlight-selected 0.13.1 
Hydrogen 2.5.1 
indent-guide-improved 1.4.13 
intentions 1.1.5 
language-vue 0.23.1 
linter 2.2.0 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
package-sync 1.1.0 
pigments 0.40.2 
tag 0.5.0 
tool-bar 1.1.7 
```

**Comment by JARVIS-AI** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.0 x64
**Electron**: 2.0.9
**OS**: Mac OS X 10.13.4
**Thrown From**: [atom-css-comb](https://github.com/jchouse/csscomb-atom) package 3.3.1


### Stack Trace

Failed to activate the atom-css-comb package

```
At only one instance of babel-polyfill is allowed

Error: only one instance of babel-polyfill is allowed
    at /packages/atom-css-comb/node_modules/babel-polyfill/lib/index.js:10:9)
    at /packages/atom-css-comb/node_modules/babel-polyfill/lib/index.js:29:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146381)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149928)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:145671)
    at /packages/atom-css-comb/node_modules/csscomb/lib/core.js:3:1)
    at /packages/atom-css-comb/node_modules/csscomb/lib/core.js:453:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146381)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149928)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:145671)
    at /packages/atom-css-comb/node_modules/csscomb/lib/csscomb.js:5:12)
    at /packages/atom-css-comb/node_modules/csscomb/lib/csscomb.js:306:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146381)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149928)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:145671)
    at /packages/atom-css-comb/lib/css-comb.js:3:41)
    at /packages/atom-css-comb/lib/css-comb.js:152:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146381)
```

### Commands

```
```

### Non-Core Packages

```
asciidoc-assistant 0.2.2 
asciidoc-image-helper 1.0.1 
asciidoc-preview 2.12.2 
atom-beautify 0.33.4 
atom-clock 0.1.16 
atom-code-ui 0.4.4 
atom-css-clean 2.24.1 
atom-css-comb 3.3.1 
atom-dark-fusion-syntax 2.2.1 
atom-html-templates 0.1.3 
atom-ide-dark-syntax 0.1.2 
atom-ide-debugger-python 0.7.3 
atom-ide-ui 0.13.0 
atom-jade 0.3.0 
atom-material-ui 2.1.3 
atom-typescript 12.6.3 
auto-indent 0.5.0 
autoclose-html 0.23.0 
autocomplete 0.47.0 
autocomplete-asciidoc 0.1.2 
autocomplete-erlang 1.1.2 
autocomplete-html-entities 0.2.0 
autocomplete-paths 2.12.2 
autocomplete-python 1.10.12 
autocomplete-swift 1.0.3 
autumn-highlighter-syntax 1.13.0 
busy-signal 1.4.3 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
color-picker 2.3.0 
dark-side-of-the-moon-syntax 0.6.62 
disable-keybindings 0.6.0 
docblockr 0.13.7 
duotone-blue-dark-syntax 1.4.0 
duotone-dark-earth-syntax 2.1.0 
duotone-dark-forest-syntax 2.1.0 
duotone-dark-sea-syntax 2.1.0 
duotone-dark-sky-syntax 2.1.0 
duotone-dark-space-syntax 2.1.0 
duotone-dark-syntax 2.1.0 
duotone-light-syntax 2.1.0 
duotone-snow 2.2.0 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.26 
firefox-syntax 4.2.0 
firewatch-syntax 1.1.1 
flow-ide 1.12.1 
git-plus 8.1.0 
highlight-selected 0.14.0 
html-to-css 0.2.2 
hydra-syntax-theme 4.0.1 
hyperclick 0.0.0 
hyperlink-hyperclick 2.0.0 
ide-cpp 0.0.3 
ide-css 0.3.0 
ide-flowtype 0.24.0 
ide-go 0.12.3 
ide-haskell 2.3.1 
ide-html 0.4.2 
ide-json 0.2.1 
ide-r 0.1.8 
ide-rust 0.18.4 
ide-swift 0.1.8 
ide-typescript 0.7.9 
ide-vue 0.1.9 
ide-yaml 0.4.4 
jackhammer-syntax 1.1.0 
language-asciidoc 1.11.0 
language-awk 0.1.12 
language-babel 2.85.0 
language-dtd 0.2.1 
language-elixir 0.22.1 
language-elm 1.5.0 
language-erlang 3.2.0 
language-fortran 2.1.7 
language-gitignore 0.3.0 
language-haskell 1.17.8 
language-hcl 0.4.0 
language-ini-desktop 1.18.3 
language-log 1.10.1 
language-lua 0.9.11 
language-markdown 0.27.0 
language-pascal 1.0.0 
language-powershell 5.0.0 
language-prolog 0.11.0 
language-qml 1.1.0 
language-qt-qrc 3.0.0 
language-restructuredtext 1.1.2 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-vex 0.1.3 
language-vue 0.23.1 
language-vue-component 0.5.0 
linter 2.2.0 
linter-eslint 8.4.1 
markdown-preview-enhanced 0.15.8 
markdown-preview-plus 3.7.0 
markdown-table-editor 1.1.1 
markdown-writer 2.10.3 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
multi-cursor 2.1.5 
NewFirewatch-syntax 1.2.0 
night-owl-syntax 1.0.1 
no-title-bar 1.11.4 
oceanic-next 1.0.0 
oceanic-reef-syntax 0.9.0 
operator-mono 0.11.0 
pigments 0.40.2 
pretty-json 2.0.3 
pristine-ui 1.1.11 
restart-atom 0.2.0 
script 3.18.1 
sort-lines 0.18.0 
spacegray-atom-dark-syntax 1.3.2 
spacegray-dark-neue-syntax 1.4.2 
spacegray-dark-neue-ui 1.7.1 
spacegray-dark-ui 0.13.0 
spacegray-eighties-ui 2.0.0 
split-diff 1.5.3 
styri-syntax 1.0.0 
svg-preview 0.14.0 
swift-debugger 0.1.2 
tidy-markdown 3.0.1 
tomorrow-night-eighties-syntax 1.1.0 
tool-bar 1.1.11 
tool-bar-atom 1.7.0 
tool-bar-main 0.0.11 
tool-bar-markdown-writer 0.5.0 
tree-view-autoresize 2.3.0 
tree-view-git-status 1.5.2 
ubik-gotham-syntax 1.2.0 
unity-ui 2.1.11 
```

**Comment by robamler** [comment]
I get the same error when I start atom or open a project.

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Ubuntu 17.10
**Thrown From**: [atom-css-comb](https://github.com/jchouse/csscomb-atom) package 3.3.1


### Stack Trace

Failed to activate the atom-css-comb package

```
At only one instance of babel-polyfill is allowed

Error: only one instance of babel-polyfill is allowed
    at /packages/atom-css-comb/node_modules/babel-polyfill/lib/index.js:10:9)
    at /packages/atom-css-comb/node_modules/babel-polyfill/lib/index.js:29:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145675)
    at /packages/atom-css-comb/node_modules/csscomb/lib/core.js:3:1)
    at /packages/atom-css-comb/node_modules/csscomb/lib/core.js:453:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145675)
    at /packages/atom-css-comb/node_modules/csscomb/lib/csscomb.js:5:12)
    at /packages/atom-css-comb/node_modules/csscomb/lib/csscomb.js:306:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145675)
    at /packages/atom-css-comb/lib/css-comb.js:3:41)
    at /packages/atom-css-comb/lib/css-comb.js:152:2)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146385)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-css-comb 3.3.1 
atom-ide-ui 0.13.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
autocomplete-python 1.11.0 
busy-signal 1.4.3 
docblock-python 0.10.0 
document-outline 2.1.2 
file-icons 2.1.26 
git-plus 8.1.0 
Hydrogen 2.6.0 
ide-python 1.0.0 
indent-detective 0.3.0 
ink 0.9.12 
intentions 1.1.5 
javascript-snippets 1.2.1 
julia-client 0.7.10 
language-julia 0.18.0 
language-latex 1.2.0 
latex 0.50.0 
latex-completions 0.3.5 
linter 2.2.0 
linter-spell 0.15.0 
linter-spell-latex 0.11.0 
linter-spell-latexsimple 0.4.0 
linter-ui-default 1.7.1 
linter-write-good 0.9.0 
minimap 4.29.9 
pdf-view 0.71.0 
python-debugger 0.2.0 
python-indent 1.1.6 
python-tools 0.6.9 
tab-control 0.6.11 
tabs-to-spaces 1.0.5 
tool-bar 1.1.11 
uber-juno 0.2.0 
wordcount 3.0.0 
```

**Comment by latheeshvmv** [comment]
Me too! 👍

**Comment by inuitviking** [comment]
Still experiencing it in 2019. Any update on this?

[Enter steps to reproduce:]
1.Open a project or turn on Atom

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Pop!_OS 18.04 (This is basically Ubuntu 18.04)
**Thrown From**: [atom-css-comb](https://github.com/jchouse/csscomb-atom) package 3.3.1


### Stack Trace

Failed to activate the atom-css-comb package

```
At only one instance of babel-polyfill is allowed

Error: only one instance of babel-polyfill is allowed
    at /packages/atom-css-comb/node_modules/babel-polyfill/lib/index.js:10:9)
    at /packages/atom-css-comb/node_modules/babel-polyfill/lib/index.js:29:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145974)
    at /packages/atom-css-comb/node_modules/csscomb/lib/core.js:3:1)
    at /packages/atom-css-comb/node_modules/csscomb/lib/core.js:453:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145974)
    at /packages/atom-css-comb/node_modules/csscomb/lib/csscomb.js:5:12)
    at /packages/atom-css-comb/node_modules/csscomb/lib/csscomb.js:306:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145974)
    at /packages/atom-css-comb/lib/css-comb.js:3:41)
    at /packages/atom-css-comb/lib/css-comb.js:152:2)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146684)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-css-comb 3.3.1 
atom-ide-ui 0.13.0 
autoclose-html 0.23.0 
color-picker 2.3.0 
disable-mru-tabbing 0.4.0 
emmet 2.4.3 
file-icons 2.1.28 
git-plus 8.4.2 
html-to-css 0.2.2 
ide-html 0.5.0 
ide-json 0.2.1 
ide-php 0.7.18 
minimap 4.29.9 
remote-ftp 2.2.2 
teletype 0.13.3 
```

**Comment by ProUnebit** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 ia32
**Electron**: 2.0.16
**OS**: Unknown Windows version
**Thrown From**: [atom-css-comb](https://github.com/jchouse/csscomb-atom) package 3.3.1


### Stack Trace

Failed to activate the atom-css-comb package

```
At only one instance of babel-polyfill is allowed

Error: only one instance of babel-polyfill is allowed
    at /packages/atom-css-comb/node_modules/babel-polyfill/lib/index.js:10:9)
    at /packages/atom-css-comb/node_modules/babel-polyfill/lib/index.js:29:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:145974)
    at /packages/atom-css-comb/node_modules/csscomb/lib/core.js:3:1)
    at /packages/atom-css-comb/node_modules/csscomb/lib/core.js:453:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:145974)
    at /packages/atom-css-comb/node_modules/csscomb/lib/csscomb.js:5:12)
    at /packages/atom-css-comb/node_modules/csscomb/lib/csscomb.js:306:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:145974)
    at /packages/atom-css-comb/lib/css-comb.js:3:41)
    at /packages/atom-css-comb/lib/css-comb.js:152:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146684)
```

### Commands

```
```

### Non-Core Packages

```
angularjs 0.5.3 
atom-beautify 0.33.4 
atom-bootstrap4 1.4.0 
atom-css-comb 3.3.1 
atom-html-preview 0.2.6 
atom-import-cost 1.2.0 
atom-live-server 2.3.0 
atom-ternjs 0.18.3 
atom-typescript 13.1.0 
autocomplete-json 5.5.2 
autocomplete-modules 2.2.6 
autocomplete-paths 2.12.2 
blade-spacer 0.4.2 
bracket-colorizer 1.2.0 
busy-signal 2.0.0 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
color-picker 2.3.0 
colorblind-wombat-dark-syntax 0.6.0 
console-log 1.10.0 
dash 1.7.1 
emmet 2.4.3 
es6-javascript 1.0.0 
export-html 3.1.0 
file-icons 2.1.29 
git-plus 8.4.2 
git-time-machine 2.1.0 
gsap-snippets 0.5.0 
highlight-selected 0.14.0 
indent-guide-improved 1.4.13 
intentions 1.1.5 
jade-beautify 0.1.5 
javascript-snippets 1.2.1 
jquery-snippets 11.0.0 
json-colorer 1.0.0 
language-babel 2.85.0 
language-ejs 0.4.0 
language-jade 0.7.3 
language-javascript-jsx 0.3.7 
language-mjml 2.0.1 
language-postcss 1.3.1 
language-vue 0.24.0 
linter 2.3.0 
linter-eslint 8.5.1 
linter-mjml 1.2.0 
linter-php 1.6.0 
linter-ui-default 1.7.1 
markdown-pdf 2.2.0 
markdown-writer 2.11.4 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
minimap-split-diff 0.3.7 
mjml-preview 2.0.1 
nav-panel 0.0.11 
node-debugger 1.10.1 
nodejs-snippets 2.0.2 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
open-in-browser 0.5.2 
open-recent 5.0.0 
path-copy 0.14.0 
pigments 0.40.2 
pretty-json 2.0.3 
pristine-ui 1.1.11 
ramda-syntax 1.0.4 
react 0.18.0 
script 3.18.1 
simple-drag-drop-text 0.4.0 
sort-lines 0.18.0 
sorter 1.2.1 
split-diff 1.6.0 
Stylus 3.2.0 
svg-preview 0.14.0 
todo-show 2.3.2 
tool-bar 1.1.11 
tool-bar-main 0.0.11 
```
