### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getSelectedText' of undefined

### ISSUE THREAD

**Issue by sandro-git** [jchouse/csscomb-atom#33]
[Enter steps to reproduce:]

1. make personal config on site 
2.create the .csscomb.json file in the main folder
3. launch with command palette

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [atom-css-comb](https://github.com/jchouse/csscomb-atom) package 3.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getSelectedText' of undefined

```
At /Users/sandro/.atom/packages/atom-css-comb/lib/css-comb.js:103

TypeError: Cannot read property 'getSelectedText' of undefined
    at Object._getSelectedText (/packages/atom-css-comb/lib/css-comb.js:103:52)
    at Object.comb (/packages/atom-css-comb/lib/css-comb.js:113:33)
    at /packages/atom-css-comb/lib/css-comb.js:61:39)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:106:35)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:313:26)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:81:20)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -3:21.3.0 tree-view:add-file (ol.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:09.6.0 core:confirm (input.hidden-input)
     -3:04.8.0 autocomplete-plus:confirm (input.hidden-input)
     -3:03.7.0 intentions:highlight (input.hidden-input)
     -3:02.8.0 editor:newline (input.hidden-input)
     -3:01.2.0 core:backspace (input.hidden-input)
     -3:00.7.0 core:move-down (input.hidden-input)
  2x -3:00.4.0 core:backspace (input.hidden-input)
  2x -2:53.7.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
     -2:41.8.0 css-comb:comb (input.hidden-input)
     -2:39.7.0 core:save (input.hidden-input)
     -2:37.4.0 css-comb:comb (input.hidden-input)
     -2:07.8.0 settings-view:open (input.hidden-input)
     -0:47.3.0 command-palette:toggle (select#atom-css-comb.readyMadeConfigs.form-control)
     -0:43.4.0 core:confirm (input.hidden-input)
     -0:43.4.0 css-comb:comb (select#atom-css-comb.readyMadeConfigs.form-control)
```

### Non-Core Packages

```
atom-css-comb 3.1.0 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.0.4 
atom-pug 0.2.0 
atom-ternjs 0.18.3 
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.7 
intentions 1.1.2 
linter 2.2.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.2 
w3c-validation 0.4.0 
```

**Comment by iyutalo** [comment]
Please check `config.cson`.

```
"*":
  "atom-css-comb":
    commonConfigs: "/Users/username/.csscomb.json"
```
↓
```
"*":
  "atom-css-comb":
    commonConfig: "/Users/username/.csscomb.json"
```

`commonConfigs` is supposed to be `commonConfig`.

**Comment by jchouse** [comment]
Just type in `Use project config` input, name of your file `.csscomb.json`
