### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getGrammar' of undefined

### ISSUE THREAD

**Issue by BlckBob** [jchouse/csscomb-atom#37]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 ia32
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-css-comb](https://github.com/jchouse/csscomb-atom) package 3.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getGrammar' of undefined

```
At C:\Users\Boban\AppData\Local\atom\app-1.18.0\resources\app\src\pane.js:1095

TypeError: Cannot read property 'getGrammar' of undefined
    at Object._getSytax (/packages/atom-css-comb/lib/css-comb.js:108:58)
    at /packages/atom-css-comb/lib/css-comb.js:99:23
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.saveAs (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:1119:26)
    at TextBuffer.module.exports.TextBuffer.save (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:1108:25)
    at TextEditor.module.exports.TextEditor.save (~/AppData/Local/atom/app-1.18.0/resources/app/src/text-editor.js:925:32)
    at Pane.module.exports.Pane.saveItem (~/AppData/Local/atom/app-1.18.0/resources/app/src/pane.js:780:24)
    at Pane.saveItem (~/AppData/Local/atom/app-1.18.0/resources/app/src/pane.js:3:65)
    at Pane.module.exports.Pane.saveItems (~/AppData/Local/atom/app-1.18.0/resources/app/src/pane.js:827:22)
    at PaneContainer.saveAll (~/AppData/Local/atom/app-1.18.0/resources/app/src/pane-container.js:175:52)
    at WorkspaceCenter.saveAll (~/AppData/Local/atom/app-1.18.0/resources/app/src/workspace-center.js:265:30)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/workspace.js:1526:25
    at Array.forEach (native)
    at Workspace.saveAll (~/AppData/Local/atom/app-1.18.0/resources/app/src/workspace.js:1525:38)
    at atom-workspace.window:save-all (~/AppData/Local/atom/app-1.18.0/resources/app/src/register-default-commands.js:218:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.18.0/resources/app/src/atom-environment.js:1314:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.18.0/resources/app/src/application-delegate.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
 13x -5:56.8.0 intentions:highlight (input.hidden-input)
     -5:50.6.0 core:save (input.hidden-input)
     -2:12.4.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -2:12.4.0 editor:newline (input.hidden-input)
     -1:18.4.0 core:backspace (input.hidden-input)
     -1:07.4.0 window:save-all (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
aligner-scss 1.3.1 
atom-autocomplete-php 0.25.6 
atom-bootstrap3 1.2.12 
atom-clock 0.1.13 
atom-css-comb 3.3.0 
atom-django 0.3.2 
atom-html-preview 0.1.22 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-sass 0.4.0 
atom-ternjs 0.18.3 
atomic-chrome 0.3.0 
autocomplete-python 1.9.1 
autoprefixer 3.7.1 
build 0.68.0 
build-sass 0.11.0 
busy 0.7.0 
busy-signal 1.4.3 
coffee-compile 0.26.0 
css-snippets 1.1.0 
django-templates 0.5.0 
emmet 2.4.3 
file-icons 2.1.9 
hey-pane 1.0.0 
intentions 1.1.2 
kite 0.30.1 
linter 2.2.0 
linter-php 1.3.2 
linter-sass-lint 1.7.4 
linter-scss-lint 3.1.0 
linter-ui-default 1.6.2 
linter-write-good 0.9.0 
livestyle-atom 0.2.9 
pigments 0.39.1 
python-tools 0.6.9 
qolor 0.4.2 
Sass-Syntax-Highlight 0.1.1 
scss-media-queries 0.4.0 
wordpress-api 1.2.2 
```

**Comment by jchouse** [comment]
cannot reproduce
